version: '3.9'

services:
  fastapi:
    build:
      context: ./app/fastapi
      dockerfile: ../../docker/Dockerfile-FastAPI
    ports:
      - "8000:8000"
    volumes:
      - ./app/fastapi:/usr/src/app/fastapi
    networks:
      - app-network
  react:
    build:
      context: ./app/ytmp3-react
      dockerfile: ../../docker/Dockerfile-React
    ports:
      - "3000:3000"
    volumes:
      - ./app/ytmp3-react:/usr/src/app/ytmp3-react
    networks:
      - app-network
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
