version: '3.9'

services:
  web:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
